config/routes.rb
Rails.application.routes.draw do
  
  get 'reviews/create'

  get 'reviews/destroy'
  get 'aboutus' => 'aboutus#aboutus'
  get 'comments/create'
  get 'comments/destroy'
  resources :comments, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  devise_for :users
  
  root 'cloths#index'
  get 'cloths/men_top'=> 'cloths#men_top'
  get 'cloths/men_bottom'=>'cloths#men_bottom'
  get 'cloths/men_jeans'=>'cloths#men_jeans'
  get 'cloths/men_shoes'=>'cloths#men_shoes'
  
  
  resources :cloths do
    collection do
      get :search
    end
  end
  get 'cloths/search' => 'cloths#search'

  get '/editinfo' => 'editinfo#editinfo'
  get '/mypage' => 'mypage#mypage'
 
 

end

app/models/cloth.rb
require 'nokogiri'
require 'open-uri'

class Cloth < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    has_many :reviews, dependent: :destroy
    mount_uploader :image1, ImgUploader
    mount_uploader :image2, ImgUploader
    mount_uploader :image3, ImgUploader
    # mount_uploader :image4, ImgUploader
   
  paginates_per 4
  validates_presence_of :name
  searchable do
    text :name
  end
  
  def self.search(search)
      search = "%#{search.downcase}%"    
        where("lower(name) LIKE ?", "%#{search}%") 
  end
  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :cloth
end

app/models/review.rb
require 'nokogiri'
require 'open-uri'

class Review < ActiveRecord::Base
  belongs_to :cloth
  #무신사 크롤링
  # url = "http://store.musinsa.com/app/product/detail/735721/0"
  # #노코기리 파서로 HTML 형태로 분류한 형태의 데이터를 data 변수에 저장한다.
  # data = Nokogiri::HTML(open(url))
  # #.css selector로 tbody 안의 tr 내용들만 가져온다.
  # @reviews = data.css('.galleryList .nslist_post')

  # @reviews.each do |review|
  #   Review.create(
  #     :shop => "musinsa",
  #     :price => "25500",
  #     :size => review.css('div.postRight div.postContents div.content_object a span').text.strip,
  #     :content => review.css('div.postRight div.postContents div.pContent div.summary div.cArea div.pContent_text span').text.strip,
  #     :date => review.css('div.postRight div.postContents div.profile p span.date').text.strip,
  #     :image => ""
  #   )
  # end
  
  # #옥션 크롤링
  # url = "http://itempage3.auction.co.kr/DetailView.aspx?itemno=B512089607"
  # #노코기리 파서로 HTML 형태로 분류한 형태의 데이터를 data 변수에 저장한다.
  # data = Nokogiri::HTML(open(url))
  # #.css selector로 tbody 안의 tr 내용들만 가져온다.
  # @reviews = data.css('tbody tr')

  # @reviews.each do |review|
  #   Review.create(
  #     :shop => "Auction",
  #     :price => "25920",
  #     :size => review.css('td div.coment-wrap div.coment-title em.option span').text.strip,
  #     :content => review.css('td div.coment-wrap p.coment').text.strip,
  #     :date => review.css('td.coment-info ul li.date').text.strip,
  #     :image => ""
  #   )
  # end
  
  # #쿠팡 크롤링
  # url = "http://www.coupang.com/vp/products/61166033?itemId=209724941&vendorItemId=3497300186&
  # q=%EC%B9%BC%ED%95%98%ED%8A%B8+%EB%B0%98%ED%8C%94%ED%8B%B0&itemsCount=36&searchId
  # =ce360ae8d9eb46d0aae94d56328e1688&rank=0"
  # #노코기리 파서로 HTML 형태로 분류한 형태의 데이터를 data 변수에 저장한다.
  # data = Nokogiri::HTML(open(url))
  # #.css selector로 tbody 안의 tr 내용들만 가져온다.
  # @reviews = data.css('selection.js_reviewArticleListContainer')

  # @reviews.each do |review|
  #   Review.create(
  #     :shop => "Coupang",
  #     :price => "26900",
  #     :size => review.css('article.js_reviewArticleReviewList div.sdp-review__article__list__info div.sdp-review__article__list__info__product-info__name').text.strip,
  #     :content => review.css('article.js_reviewArticleReviewList div.sdp-review__article__list__review js_reviewArticleContentContainer div.sdp-review__article__list__review__content js_reviewArticleContent').text.strip,
  #     :date => review.css('article.js_reviewArticleReviewList div.sdp-review__article__list__info div.sdp-review__article__list__info__product-info div.sdp-review__article__list__info__product-info__reg-date').text.strip,
  #     :image => ""
  #   )
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
    def aboutus
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:sex])
    devise_parameter_sanitizer.permit(:account_update, keys: [:sex])
  end
end

app/controllers/cloths_controller.rb
class ClothsController < ApplicationController
  before_action :set_cloth, only: [:show, :edit, :update, :destroy]

  def men_top
    if params[:query]
      @cloths = Cloth.search(params[:query]).order("created_at DESC").page params[:page]
    else
      @cloths = Cloth.where(:sex =>'m').order("created_at DESC").page params[:page]
      # @cloths = Cloth.order("created_at DESC")
    end
  end
  
  def men_bottom
  end

  def men_jeans
  end
  def men_shoes
  end
  # GET /cloths
  # GET /cloths.json
  def index
    @cloth_page = nil
    if params[:query]
      @cloths = Cloth.search(params[:query]).order("created_at DESC").page params[:page]
    else
      @cloths = Cloth.where(:sex =>'w').order("created_at DESC").page params[:page]
      # @cloths = Cloth.order("created_at DESC").page params[:page]
    end
  end
  


  # GET /cloths/1
  # GET /cloths/1.json
  def show
    @reviews = Review.order("RANDOM()").page(params[:page]).per(8)
  end

  # GET /cloths/new
  def new
    @cloth = Cloth.new
  end

  # GET /cloths/1/edit
  def edit
  end
  
  

  # POST /cloths
  # POST /cloths.json
  def create
    @cloth = Cloth.new(cloth_params)

    respond_to do |format|
      if @cloth.save
        format.html { redirect_to @cloth, notice: '' }
        format.json { render :show, status: :created, location: @cloth }
      else
        format.html { render :new }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloths/1
  # PATCH/PUT /cloths/1.json
  def update
    respond_to do |format|
      if @cloth.update(cloth_params)
        format.html { redirect_to @cloth, notice: '' }
        format.json { render :show, status: :ok, location: @cloth }
      else
        format.html { render :edit }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloths/1
  # DELETE /cloths/1.json
  def destroy
    @cloth.destroy
    respond_to do |format|
      format.html { redirect_to cloths_url, notice: 'Cloth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloth
      @cloth = Cloth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloth_params
      params.require(:cloth).permit(:sex, :category, :name, :size, :price, :brand, :image1, :image2, :image3, :image4)
    end
    
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment=Comment.new
    comment.content=params[:comment][:content]
    comment.cloth_id=params[:comment][:cloth_id]
    comment.save
    redirect_to :back
  end

  def destroy
    @destroy_comment= Comment.find(params[:id])
    @destroy_comment.destroy
    redirect_to :back
  end
end

app/controllers/editinfo_controller.rb
class EditinfoController < ApplicationController
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def mypage
      
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editinfo_helper.rb
module EditinfoHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/aboutus/aboutus.html.erb
<%= image_tag "aboutus_moamoa.jpg", class: "main_img" %>

<br>
<br>
<br>
<br>
<h6 style="text-align: center;">We’ve launched a service, MOAMOA, that provides literally all of the reviews 
about items you’ve been looking for so you can easily find what you want.</h6>
<br>
<br>
<br>
<br>
<br>
<br>
<%= image_tag "kak.jpg", class: "main_img" %>

app/views/cloths/_form.html.erb
<%= form_for(@cloth) do |f| %>
  <% if @cloth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cloth.errors.count, "error") %> prohibited this cloth from being saved:</h2>

      <ul>
      <% @cloth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="j-container">
  <div class="row">
    <div class=" col-xl-3"></div>
    <div class=" col-xl-6">
     
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      
      <div class="field">
        <%= f.label :brand %><br>
        <%= f.text_field :brand %>
      </div>
      
      <div class="field">
        <%= f.label :category, 'Category (top,bottom,dress,shoes)'%><P></P>
        <%= f.text_field :category %>
      </div>
      
      <div class="field">
        <%= f.label :sex, 'Sex (w,m)' %><p></p>
        <%= f.text_field :sex %>
      </div>
      
      
      
      
      <div class="field">
        <%= f.label :size, "무신사스토어 Link"%>
        <input style="height: 30px; width: 320px;" type="text" name="name" required>
      </div>
      
      <div class="field">
        <%= f.label :price, "쿠팡 Link" %><br>
        <input style="height: 30px; width: 320px;" type="text" name="name" required>
      </div>
      
      <div class="field">
        <%= f.label :image4, "옥션 Link" %><br>
        <input style="height: 30px; width: 320px;" type="text" name="name" required>
      </div>
      
      <div class="field">
        <%= f.label :image1 %><br>
        <%= f.file_field :image1, accept: 'image/png,image/gif,image/jpeg' %>
      </div>
      <div class="field">
        <%= f.label :image2 %><br>
        <%= f.file_field :image2, accept: 'image/png,image/gif,image/jpeg' %>
      </div>
      <div class="field">
        <%= f.label :image3 %><br>
        <%= f.file_field :image3, accept: 'image/png,image/gif,image/jpeg' %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
    <div class =" col-xl-3"></div>
    <% end %>
  </div>
</div>

app/views/cloths/edit.html.erb
<h1>Editing Cloth</h1>

<%= render 'form' %>

<%= link_to 'Show', @cloth %> |
<%= link_to 'Back', cloths_path %>

app/views/cloths/index.html.erb
<p id="notice"><%= notice %></p>




<%= image_tag "main_women.jpg", class: "main_img" %>


<div class="bg-div">
 <% if user_signed_in?%>
   <%= link_to image_tag("add_icon.png", class: "upload_btn"), new_cloth_path %>
 <% else %> 
   <%=link_to image_tag("add_icon.png", class: "upload_btn"), new_user_session_path %>
 <%end%>
</div>

<div class="nowtrending_text">
 <h2>Check Out The Best Items For You!</h2>

 
</div>

<section class="nowtrending">
  <div class='row'>
    <% @cloths.each do |cloth| %>
      <% if cloth.sex == "w" %>
        <% @cloth_page = cloth %>
        <div class="col-sm-12 col-md-6 col-xl-3">
          <a href = "/cloths/<%= cloth.id %>" class="p_visit">  
            <div class="card">
              <div>
                <%= image_tag("heart_empty.png", class: "a-heart_empty") %>
                <% if !cloth.image1.blank? %>
                  <img class="card_img" src="<%= cloth.image1 %>" alt="Card image cap">
                <% else %>
                  <%= image_tag("placeholder_fest.jpeg", class: "card-img-top h-img") %>
                <% end %>
  
              </div>
              <div class="container">
                <h6><b><%= cloth.name %></b></h6>
                <p><%= cloth.category %></p>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
</section>

<div style="margin-right: 37%;">
  <%= paginate @cloths %>
</div>



<!-- cloths.scss에서 css수정  -->


<%= image_tag "logo_bottom.png", class: "logo_bottom" %>

app/views/cloths/men_bottom.html.erb
<div class="cartegory_top" style="text-align: center;">
<h1>Men_bottom</h1>
</div>


<div class="card_cartegory">
  <div class='row'>
 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>

 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>
    
 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>
    
 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>
    
 
    <div class='col-xl-3'>
      <div class="card">
        <%= image_tag "main_men.jpg", class: "card_img" %>
        <div class="container">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>

 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>
    
 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>
    
 
    <div class='col-xl-3'>
      <div class="sjcard">
        <%= image_tag "main_men.jpg", class: "sjcard_img" %>
        <div class="sjcontainer">
          <h6><b>John Doe</b></h6>
          <p>Architect & Engineer</p>
        </div>
      </div>
    </div>
    
  </div>
</div>


<%= image_tag "logo_bottom.png", class: "logo_bottom" %>

app/views/cloths/men_top.html.erb
<p id="notice"><%= notice %></p>




<%= image_tag "main_men.jpg", class: "main_img" %>

<div class="bg-div">
 <% if user_signed_in?%>
   <%= link_to image_tag("add_icon.png", class: "upload_btn"), new_cloth_path %>
 <% else %>
   <%=link_to image_tag("add_icon.png", class: "upload_btn"), new_user_session_path %>
 <%end%>
</div>
 


<div class="nowtrending_text">
 <h2>Check Out The Best Items For You!</h2>
</div>

<section class="nowtrending">
  <div class='row'>
    <% @cloths.each do |cloth| %>
    
      <% if cloth.sex == "m" %>
        <div class="col-sm-12 col-md-6 col-xl-3">
          <a href = "/cloths/<%= cloth.id %>" class="p_visit">  
            <div class="card">
              <div>
                <%= image_tag("heart_empty.png", class: "a-heart_empty") %>
                <% if !cloth.image1.blank? %>
                  <img class="card_img" src="<%= cloth.image1 %>" alt="Card image cap">
                <% else %>
                  <%= image_tag("placeholder_fest.jpeg", class: "card-img-top h-img") %>
                <% end %>
  
              </div>
              <div class="container">
                <h6><b><%= cloth.name %></b></h6>
                <b><%= cloth.category %></b>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
    

</section>
<div style="margin-right: 34%;">
  <%= paginate @cloths %>
</div>


<%= image_tag "logo_bottom.png", class: "logo_bottom" %>

app/views/cloths/new.html.erb
<h1 class="upload_text">New Cloth</h1>
 
<div class="upload_form">
 <div class="container_upload">   
  <%= render 'form' %>
  <br>
  <div class="upload_back">
   <%= link_to 'Back', cloths_path %>
  </div>
  <br>
 </div> 
</div>

app/views/cloths/show.html.erb
<p id="notice"><%= notice %></p>

<div style="margin-top:70px;"></div>


  <div class="row">
    <div class=" col-xl-1"></div>
    
    
      <div class=" col-xl-3">
        <p>
          <img class=img1 src = '<%= @cloth.image1 %>'/>
        </p>
      </div>
      
    
      <div class=" col-xl-2">
        <p>
          <img class=img2 src = '<%= @cloth.image2 %>'/>
        </p>

        <p>
          <img class=img2 src = '<%= @cloth.image3 %>'/>
        </p>
      </div>
    
    <div class=" col-xl-1"></div>
    
    <div class=" col-xl-4">
        
        <p style="line-height: 1rem, width: 400px;">
         <font size="6"><%= @cloth.name %></font>
        </p>
        
      <br>
          <div style="overflow:scroll; width:400px; height:340px;">
        
        <ul class="list-group">
          <a href ='http://store.musinsa.com/app/product/detail/735723/0'><li class="list-group-item">무신사스토어    ₩25500</li></a>
          <a href = 'http://itempage3.auction.co.kr/DetailView.aspx?itemno=B512089607'><li class="list-group-item">Auction   ₩25290</li></a>
          <a href = 'http://www.coupang.com/vp/products/61166033?itemId=209724941&vendorItemId=3497300186&q=%EC%B9%BC%ED%95%98%ED%8A%B8+%EB%B0%98%ED%8C%94%ED%8B%B0&itemsCount=36&searchId=ce360ae8d9eb46d0aae94d56328e1688&rank=0'><li class="list-group-item">Coupang        ₩26900</li></a>
          <a href= '#' class = 'p_font_color'><li class="list-group-item">Wating For...</li></a>
          <a href= '#' class = 'p_font_color'><li class="list-group-item">Wating For...</li></a>
          <a href= '#' class = 'p_font_color'><li class="list-group-item">Wating For...</li></a>
          <a href= '#' class = 'p_font_color'><li class="list-group-item">Wating For...</li></a>
          <a href= '#' class = 'p_font_color'><li class="list-group-item">Wating For...</li></a>
          <a href= '#' class = 'p_font_color'><li class="list-group-item">Wating For...</li></a>
          
          
        </ul>
        
      </div>
    </div>  
  <div class=" col-xl-2"> </div>
  </div>  

    
    <div style="margin: 100px;"></div>
    
<section class="sjreviewpt">
  <p class="reviewtitle">Reviews</p>
  
</section>

    <div style="margin: 30px;"></div>

<%@reviews.each do |review|%>
  <section class="a-container_review">
    <div class="row">
      <div>
        <p class="sjmid">  
          <strong>Shop:</strong>
          <%= review.shop %>
        </p>
        <p class="sjmid">  
          <strong>Size:</strong>
          <%= review.size %>
        </p>
        <p class="sjmid">  
          <strong>Date:</strong>
          <%= review.date %>
        </p>
        <p class="sjmid">  
          <strong>Content:</strong>
          <%= review.content %>
        </p>
      </div>
      <div class=" col-xl-1"></div>
  </section>
<% end %>

<div style="margin-right: 33%;">
  <%= paginate @reviews %>
</div>


<!--<div class="a-reply">          -->
 
<!--  <%= form_for Comment.new, url:comments_path do |f| %>-->
<!--    <%= f.text_field :content %>-->
<!--    <%= f.hidden_field :cloth_id, value: @cloth.id %>-->
    
<!--    <br>-->
<!--    <br>-->
<!--    <%= f.submit '댓글 쓰기' %>-->
<!--  <%end%>-->
  
<!--  <% @cloth.comments.all.each do|comment|%>-->
<!--    <br>-->
<!--    <%=comment.content%>-->
<!--    <br>-->
<!--    <%=link_to 'Destroy', comment_path(comment), method: :delete, date: { confirm: 'Are you sure?'} %>-->
<!--    <br>-->
<!--  <%end%>-->
<!--</div>-->

<div class="sjlink">
  <%= link_to 'Edit', edit_cloth_path(@cloth) %> |
  <%= link_to 'Back', cloths_path %>
</div>


<%= image_tag "logo_bottom.png", class: "logo_bottom" %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/editinfo/editinfo.html.erb
<form class="editinfo_form">
    <h1>Update your account</h1>
    <p>Please fill in this form to update your information.</p>
    <hr>
    <label class="editinfo_label"><b>Name</b></label>
    <input style="height: 45px;" type="text" placeholder="Enter Name" name="name" required>
    <br>
    <br>
    <label>
    <input type="checkbox" checked="checked" name="Male" style="margin-bottom:15px">Male
    <input type="checkbox" checked="unchecked" name="Female" style="margin-bottom:15px">Female
    </label>
    
    <br>

    <label class="editinfo_label"><b>Password</b></label>
    <input style="height: 45px;" type="password" placeholder="Enter Password" name="psw" required>
    <br>
    <br>
    <label class="editinfo_label"><b>Repeat Password</b></label>
    <input style="height: 45px;" type="password" placeholder="Repeat Password" name="psw-repeat" required>
    <br>
    <br>

    <div class="clearfix">
     <button class="editinfo_btn" type="submit" class="savebtn">Save</button>
  </div>
</form>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 
  <title>MOAMOA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="bg-div">
    

    
    <a href='/'>
      <%= image_tag "logo.png", class: "logo-img"%> 
    </a>
    
    <nav>
      <ul class="main_nav">
      
        <!--<li><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
        <!--  Men</a>-->
        
        <!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
        <!--  <a class="dropdown-item" href="/cloths/men_top">Top</a>-->
        <!--  <a class="dropdown-item" href="/cloths/men_bottom">bottom</a>-->
        <!--  <a class="dropdown-item" href="/cloths/men_jeans">jeans</a>-->
        <!--  <a class="dropdown-item" href="/cloths/men_shoes">shoes</a>-->
          
        <!--</div>-->
        
        <!--</li>-->
        <!--<li><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
        <!--  Women</a>-->
          
        <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
        <!--  <a class="dropdown-item" href="#">Top</a>-->
        <!--  <a class="dropdown-item" href="#">Dress</a>-->
        <!--  <a class="dropdown-item" href="#">Bottom</a>-->
        <!--  <a class="dropdown-item" href="#">jeans</a>-->
        <!--  <a class="dropdown-item" href="#">shoes</a>-->
        <!-- </div>-->
        
        <!--</li>-->
        <li><a href="/cloths/men_top">Men</a></li>
        <li><a href="/cloths">Women</a></li>
        <li><a href="/aboutus">About us</a></li>
        <% if user_signed_in? %>
        <li><a href="/mypage">My page</a></li>
        <li><a href='/users/sign_out' data-method="delete" >Logout</a></li>
        <%else%>
        <li><a href='/users/sign_in'>LogIn</a></li>
        <li><a href='/users/sign_up'>Sign Up</a></li>  
        <%end%>
        

        <!--<div class="row">-->
        <!--    <div class="col-4 col-md-2" style="padding-right:5px">-->
        <!--        <select name="selecto" id="selecto" class="korfont form-control form-control-sm">-->
        <!--          <option selected="selected" value="1">제목</option>-->
        <!--          <option value="2">내용</option>-->
        <!--          <option value="3">제목/내용</option></select>-->
        <!--    </div>-->
        <!--    <div class="col-5 col-md-3" style="padding-right:6px; padding-left:0px">-->
        <!--      <input type="text" name="search" id="textarea1" value="안경" placeholder="키워드를 입력해주세요" class="korfont form-control form-control-sm">-->
        <!--      </div>-->
        <!--    <div class="col-3 col-md-2" style="padding-left:0px"><button name="button" type="submit" class="btn btn-primary btn-sm korfont">찾기</button></div>-->
        <!--    <div class="col-0 col-md-5"></div>-->
        <!--</div>-->
          <li>
    <div>
      <div>
       <div class="input-group">
        <div>
         <%= form_tag '#'+ cloths_path, :method => :get do %>
         <%= text_field_tag :query, params[:query] %> 
        </div>
        <%= submit_tag "Search" %>
        <% end %>
       </div>
      </div>
    </div>
  </li>
     

      </ul>

      
      
<!-- 서치박스

      <div class="a-searchbox">
       <form id="searchThis" action="/search" style="display: inline-block;" method="get">
         <input onfocus="if(this.value==this.defaultValue)this.value='';" value="Search items" type="text" id="searchBox" onblur="if(this.value=='')this.value=this.defaultValue;" vinput="" name="q" />
         <input id="searchButton" value="go" type="submit" />
       </form>
      </div>
        -->

  
    
    </nav>
  </div>
  
 
  
  <%= yield %>
  
  </body>
</h